### ISSUE TITLE
error when I connect?

### ISSUE THREAD

**Issue by cedricalpatch** [rhapidfyre/Badges-n-Bandits#3]
{"soc":"","user":"jamie","ip":"147.78.30.109","stm":"steam:XXXXXXX","red":"","discd":""}
SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:924: No such export scalarSync in resource ghmattimysql

**Comment by cedricalpatch** [comment]
when I connect on the session or not dont any error

**Comment by rhapidfyre** [comment]
Please contact the developers of GHMattiMySQL regarding issues with their resource. Sorry for the inconvenience.
